### PR TITLE
Change to using inline array annotation for dependency injection. 

### LINKED ISSUE #2: Can't use angular-ra-newrelic with atomify/browserify + minifiy
I am using angular-ra-newrelic within a project that uses Atomify to manage our dependencies. Because angular-ra-newrelic and angular-ra-pageload use implicit annotation instead of inline array notation for injected dependencies, minifying the code breaks the app.

Would it be possible to use inline array annotation so that the module can be bundled and minified?

Also posted in red-ant/angular-ra-newrelic#1

### PR DESCRIPTION
**Pull request by ashleahhill**
Fixes #2

### CODE REVIEW

**Comment by insaineyesay** [comment]
:+1:

**Comment by wbprice** [comment]
10/10 would use.

**Comment by mrlannigan** [comment]
:+1:

**Comment by abeane** [comment]
:thumbsup:

**Comment by jsntv200** [comment]
Fixed the grunt task to annotate the un-minified js

**Pull request closed without merging**
